NAME = libft.a

SRC_MANDATORY = ft_bzero.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c ft_isprint.c\
					ft_memset.c ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_toupper.c ft_tolower.c\
					ft_strrchr.c ft_strncmp.c ft_strnstr.c ft_strchr.c ft_atoi.c ft_memcpy.c\
					ft_memmove.c ft_memchr.c ft_memcmp.c ft_calloc.c ft_strdup.c ft_putnbr_fd.c\
					ft_putstr_fd.c ft_putchar_fd.c ft_putendl_fd.c ft_strjoin.c ft_substr.c ft_itoa.c\
			 		ft_strtrim.c ft_striteri.c ft_strmapi.c ft_split.c\

SRC_BONUS = 		ft_lstsize_bonus.c ft_lstnew_bonus.c ft_lstlast_bonus.c ft_lstiter_bonus.c ft_lstdelone_bonus.c\
					ft_lstadd_front_bonus.c ft_lstadd_back_bonus.c ft_lstclear_bonus.c ft_lstmap_bonus.c\

mandatory = $(SRC_MANDATORY:.c=.o)
bonus = $(SRC_BONUS:.c=.o)
CC = cc
CFLAGS = -Wall -Wextra -Werror

$(NAME): $(mandatory)
	ar -rs $(NAME) $^
bonus: $(mandatory) $(bonus)
	ar -rs $(NAME) $^
%.o : %.c
	$(CC) $(CFLAGS) -c $^ -o $@
clean:
	rm -f *.o
fclean: clean
	rm -f $(NAME)
re: fclean all
all: $(NAME)
.PHONY: bonus clean fclean re all